version: "3.3"
services: 
    reservation-app:
        restart: on-failure
        container_name: reservation
        build: ./
        expose: 
            - "10222"
        ports:
            - 10222:8080
        environment:
            WAIT_HOSTS: mysql:3306
        depends_on:
            - docker-mysql
    
    docker-mysql:
        restart: always
        container_name: docker-mysql
        image: mysql
        environment:
            MYSQL_DATABASE: rerervation
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports: 
            - "6666:3306"
        healthcheck:
            test: "usr/bin/mysql --user=root --pasword=root --execute \"SHOW DATABASES; \""
            interval: 4s
            timeout: 20s
            retries: 5
            start_period: 30s